apiVersion: v1
kind: Pod
metadata:
  name: fortune-prestop-fail
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - "apk add fortune && fortune > /usr/share/nginx/html/quote"
      preStop:
        exec:
          command:
          - sh
          - -c
          - "echo 'Emulating a failed pre-stop hook.'; exit 1"
    ports:
    - name: http
      containerPort: 80
