apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-exec
spec:
  containers:
  - name: kubia
    image: luksa/kubia:1.0
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      exec:
        command:
        - /usr/bin/healthcheck
      periodSeconds: 1
      failureThreshold: 1
