apiVersion: v1
kind: Pod
metadata:
  name: mongodb-nfs
spec:
  volumes:
  - name: quiz-data
    nfs:
      server: 1.2.3.4
      path: /some/path
  containers:
  - name: mongodb
    image: mongo:4.4.6
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db
