apiVersion: v1
kind: Pod
metadata:
  name: demo-ephemeral-volume
spec:
  volumes:
  - name: ephemeral-volume
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
  containers:
  - name: main
    image: busybox
    command:
    - sh
    - -c
    - 'echo "This is a demo of an ephemeral volume." && sleep infinity'
    volumeMounts:
    - mountPath: /mnt/ephemeral
      name: ephemeral-volume