apiVersion: v1
kind: Pod
metadata:
  generateName: test-
spec:
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: test
  containers:
  - name: main
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "I can read from the volume; these are its files:" ;
      ls /mnt/volume ;
      sleep infinity
    volumeMounts:
      - name: volume
        mountPath: /mnt/volume
  terminationGracePeriodSeconds: 0
