apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-read-write-once
  labels:
    app: demo-read-write-once
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
