apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data-specific-volume
spec:
  storageClassName: ""
  volumeName: quiz-data
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
