apiVersion: batch/v1
kind: CronJob
metadata:
  name: starting-deadline-seconds
spec:
  startingDeadlineSeconds: 5
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sleep
            image: busybox
            command:
            - sleep
            - '1'
