apiVersion: batch/v1
kind: Job
metadata:
  name: demo-bad-sidecar
spec:
  completions: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: demo
        image: busybox
        command: ["sleep", "20"]
      - name: sidecar
        image: busybox
        command:
        - sh
        - -c
        - "while true; do echo 'Sidecar still running...'; sleep 5; done"

