apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-invalid-storage-class
spec:
  storageClassName: nonexistent-storage-class
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
