apiVersion: v1
kind: Pod
metadata:
  name: quiz-nfs
spec:
  volumes:
  - name: quiz-data
    nfs:
      server: 1.2.3.4
      path: /some/path
  containers:
  - name: quiz-api
    image: luksa/quiz-api:0.1
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:4.4.6
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db

