apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  labels:
    app: node-agent
spec:
  selector:
    matchLabels:
      app: node-agent
  template:
    metadata:
      labels:
        app: node-agent
    spec:
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
      containers:
      - name: node-agent
        image: luksa/node-agent:0.1
        imagePullPolicy: Always
        args:
        - --listen-address
        - :80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: hostproc
          mountPath: /host/proc
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          failureThreshold: 1
          httpGet:
            port: 80
            scheme: HTTP