apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kiada
  labels:
    suite: kiada
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: '*.example.com'