apiVersion: v1
kind: Service
metadata:
  name: quiz-pods
  labels:
    app: quiz
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: quiz
  ports:
  - name: mongodb
    port: 27017