apiVersion: v1
kind: Pod
metadata:
  name: quiz
  labels:
    app: quiz
    rel: stable
spec:
  volumes:
  - name: initdb
    emptyDir: {}
  - name: quiz-data
    persistentVolumeClaim:
      claimName: quiz-data
  initContainers:
  - name: installer
    image: luksa/quiz-initdb-script-installer:0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: initdb
      mountPath: /initdb.d
  containers:
  - name: quiz-api
    image: luksa/quiz-api:0.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:7
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db
    - name: initdb
      mountPath: /docker-entrypoint-initdb.d/
      readOnly: true

