apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  nfs:
    server: 1.2.3.4
    path: /some/path
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
