apiVersion: v1
kind: PersistentVolume
metadata:
  name: other-data
spec:
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: other-data
    fsType: ext4
