apiVersion: v1
kind: PersistentVolume
metadata:
  name: quiz-data
spec:
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: quiz-data
    fsType: ext4
