apiVersion: v1
kind: Pod
metadata:
  generateName: data-reader-
spec:
  volumes:
  - name: other-data
    persistentVolumeClaim:
      claimName: other-data
      readOnly: true
  containers:
  - name: reader
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - |
      echo "The files in the persistent volume and their contents:" ;
      grep ^ /other-data/* ;
      sleep infinity
    volumeMounts:
    - name: other-data
      mountPath: /other-data
    resources:
      requests:
        cpu: 1m

